# Generated by Django 3.1 on 2020-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='post_image')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
