# Generated by Django 3.1 on 2020-09-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
